AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VulnerableLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: example-function
      Principal: s3.amazonaws.com
